### ISSUE TITLE
IDA7.0，ERROR:[sync] idb is disabled

### ISSUE THREAD

**Issue by havocykp** [bootleg/ret-sync#75] opened 2021-08-02 03:59 UTC
1. IDA show 
![image](https://user-images.githubusercontent.com/43169219/127802480-a5d2360b-8c1f-4502-a108-41a3981c7f89.png)
2. err log
![image](https://user-images.githubusercontent.com/43169219/127802530-0bfd7316-7396-4dfd-8428-0614bc05bc67.png)
3. windbg show 
![image](https://user-images.githubusercontent.com/43169219/127802566-b0dd468c-ef77-46bc-a90f-c496202a71c2.png)
4. how to solve this problem,please.

**Comment by bootleg** [comment] 2021-08-02 22:01
Hi @havocykp 

ok so IDA 7.0 means Python 2. I guess the issue is with the fix I made a couple of months ago. `buffer` attribute does not exist with Python2 stdout fd.

```
Python 3.6.9 (default, Jan 26 2021, 15:33:00)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.stdout)
<_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
```

```
Python 2.7.17 (default, Feb 27 2021, 15:10:58)
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.stdout)
<open file '<stdout>', mode 'w' at 0x7f51c32b41e0>

```

Please check https://github.com/bootleg/ret-sync/commit/bc897bbcbf0c72bf9cd4c8e30f28b2f062d5c435.

**Comment by havocykp** [comment] 2021-08-03 01:24
Hi，have solved the problem , Thanks。
![image](https://user-images.githubusercontent.com/43169219/127943022-242327cb-e498-454c-a5c7-a70e8936b72b.png)
![image](https://user-images.githubusercontent.com/43169219/127943065-9f556d1c-79c5-4f13-8e87-79a3dd7f0264.png)
![image](https://user-images.githubusercontent.com/43169219/127942991-1f926d16-8c8a-41ef-ac09-123b90ec258a.png)

**Comment by bootleg** [comment] 2021-08-03 08:16
Perfect then. Thank you for reporting the issue.

I'll close this one, please re-open if needed.
cheers.

**Closed by bootleg** 2021-08-03 08:16 UTC
Labels: bug
